import json

notebook = {
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {"name": "ipython", "version": 3},
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.9.0"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# Last Mile Connectivity \u2014 Defection Risk Model\n",
        "This notebook trains a Random Forest model to predict commuter switch risk, evaluates it, and generates artifacts/exports for frontend applications."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "import sys, os, json, warnings\n",
        "warnings.filterwarnings(\"ignore\")\n",
        "\n",
        "ASSETS = \"/home/claude/project/nb_assets\"\n",
        "OUT = \"/home/claude/project/model_outputs\"\n",
        "os.makedirs(ASSETS, exist_ok=True)\n",
        "os.makedirs(OUT, exist_ok=True)\n",
        "\n",
        "# ---- C1: Imports ----\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "import matplotlib.ticker as mticker\n",
        "from scipy import stats\n",
        "from sklearn.model_selection import train_test_split\n",
        "from sklearn.pipeline import Pipeline\n",
        "from sklearn.compose import ColumnTransformer\n",
        "from sklearn.preprocessing import StandardScaler, OneHotEncoder\n",
        "from sklearn.impute import SimpleImputer\n",
        "from sklearn.ensemble import RandomForestClassifier\n",
        "from sklearn.metrics import (\n",
        "    accuracy_score, classification_report, confusion_matrix,\n",
        "    roc_auc_score, RocCurveDisplay\n",
        ")\n",
        "import joblib\n",
        "\n",
        "plt.rcParams.update({\n",
        "    \"figure.facecolor\": \"#0f1115\",\n",
        "    \"axes.facecolor\": \"#0f1115\",\n",
        "    \"savefig.facecolor\": \"#0f1115\",\n",
        "    \"axes.edgecolor\": \"#8a8f98\",\n",
        "    \"axes.labelcolor\": \"#f5f5f5\",\n",
        "    \"text.color\": \"#f5f5f5\",\n",
        "    \"xtick.color\": \"#dcdcdc\",\n",
        "    \"ytick.color\": \"#dcdcdc\",\n",
        "    \"axes.titleweight\": \"bold\",\n",
        "    \"font.size\": 11,\n",
        "    \"axes.grid\": True,\n",
        "    \"grid.color\": \"#2a2e36\",\n",
        "    \"grid.alpha\": 0.6,\n",
        "})\n",
        "ACCENT = \"#00E5A8\"      # bold teal-green accent\n",
        "ACCENT_2 = \"#FF5C7A\"    # bold coral accent for Pune / highlights\n",
        "ACCENT_3 = \"#4EA8FF\"    # blue accent\n",
        "\n",
        "RANDOM_STATE = 42\n",
        "print(\"Libraries loaded: numpy, pandas, matplotlib, scipy, scikit-learn, joblib, os\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ---- C2: Load dataset ----\n",
        "DATA_CANDIDATES = [\n",
        "    \"last_mile_connectivity_synthetic.csv\",\n",
        "    \"/mnt/user-data/uploads/last_mile_connectivity_synthetic.csv\",\n",
        "    os.path.join(os.getcwd(), \"last_mile_connectivity_synthetic.csv\"),\n",
        "]\n",
        "DATA_PATH = next((p for p in DATA_CANDIDATES if os.path.exists(p)), DATA_CANDIDATES[0])\n",
        "\n",
        "df = pd.read_csv(DATA_PATH)\n",
        "print(f\"Loaded dataset from: {DATA_PATH}\")\n",
        "print(f\"Shape: {df.shape[0]:,} rows x {df.shape[1]} columns\")\n",
        "df.head()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ---- C3: Data quality check ----\n",
        "missing = df.isna().sum()\n",
        "missing = missing[missing > 0]\n",
        "print(\"Columns with missing values:\")\n",
        "print(missing if len(missing) else \"None\")\n",
        "print(\"\\nData types:\")\n",
        "print(df.dtypes.value_counts())\n",
        "print(f\"\\nDuplicate rows: {df.duplicated().sum()}\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ---- C4: City / node overview ----\n",
        "print(\"Trips per city:\")\n",
        "print(df[\"city\"].value_counts())\n",
        "print(f\"\\nUnique transit nodes: {df['transit_node_id'].nunique()}\")\n",
        "print(f\"Overall private-vehicle switch rate: {df['switched_to_private_vehicle'].mean()*100:.1f}%\")\n",
        "pune_rate = df.loc[df.city == \"Pune\", \"switched_to_private_vehicle\"].mean() * 100\n",
        "print(f\"Pune-specific switch rate: {pune_rate:.1f}%\")\n",
        "print(f\"Pune trips in dataset: {(df.city == 'Pune').sum():,}  |  Pune nodes: {df.loc[df.city=='Pune','transit_node_id'].nunique()}\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ---- C5: Feature definitions ----\n",
        "TARGET = \"switched_to_private_vehicle\"\n",
        "\n",
        "NUMERIC_FEATURES = [\n",
        "    \"distance_to_final_destination_km\", \"avg_wait_time_min\", \"transit_headway_min\",\n",
        "    \"crowding_index\", \"congestion_index_node\", \"last_mile_fare_inr\", \"walk_time_min\",\n",
        "    \"alt_mode_availability_score\", \"app_cab_wait_time_min\", \"safety_perception_score\",\n",
        "    \"last_mile_infra_score\", \"previous_negative_experience\", \"trip_satisfaction_score\",\n",
        "    \"node_latitude\", \"node_longitude\",\n",
        "]\n",
        "CATEGORICAL_FEATURES = [\n",
        "    \"city\", \"node_type\", \"time_of_day\", \"day_type\", \"weather_condition\",\n",
        "    \"commuter_age_group\", \"commuter_gender\", \"commuter_income_bracket\", \"trip_purpose\",\n",
        "]\n",
        "# mode_chosen_last_mile is deliberately EXCLUDED: it is a downstream label that\n",
        "# directly reveals the target (private vehicle chosen <=> switched == 1), so\n",
        "# including it would leak the answer instead of predicting it.\n",
        "\n",
        "FEATURES = NUMERIC_FEATURES + CATEGORICAL_FEATURES\n",
        "X = df[FEATURES].copy()\n",
        "y = df[TARGET].copy()\n",
        "print(f\"Using {len(NUMERIC_FEATURES)} numeric + {len(CATEGORICAL_FEATURES)} categorical features -> {len(FEATURES)} total\")\n",
        "print(f\"Target '{TARGET}' distribution:\\n{y.value_counts(normalize=True).round(3)}\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ---- C6: Train / test split ----\n",
        "X_train, X_test, y_train, y_test = train_test_split(\n",
        "    X, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y\n",
        ")\n",
        "print(f\"Train size: {X_train.shape[0]:,}  |  Test size: {X_test.shape[0]:,}\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ---- C7: Preprocessing + Random Forest pipeline ----\n",
        "numeric_transformer = Pipeline(steps=[\n",
        "    (\"imputer\", SimpleImputer(strategy=\"median\")),\n",
        "    (\"scaler\", StandardScaler()),\n",
        "])\n",
        "categorical_transformer = Pipeline(steps=[\n",
        "    (\"imputer\", SimpleImputer(strategy=\"most_frequent\")),\n",
        "    (\"onehot\", OneHotEncoder(handle_unknown=\"ignore\")),\n",
        "])\n",
        "preprocessor = ColumnTransformer(transformers=[\n",
        "    (\"num\", numeric_transformer, NUMERIC_FEATURES),\n",
        "    (\"cat\", categorical_transformer, CATEGORICAL_FEATURES),\n",
        "])\n",
        "\n",
        "rf_model = Pipeline(steps=[\n",
        "    (\"preprocessor\", preprocessor),\n",
        "    (\"classifier\", RandomForestClassifier(\n",
        "        n_estimators=300,\n",
        "        max_depth=14,\n",
        "        min_samples_leaf=4,\n",
        "        class_weight=\"balanced\",\n",
        "        random_state=RANDOM_STATE,\n",
        "        n_jobs=-1,\n",
        "    )),\n",
        "])\n",
        "print(rf_model)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ---- C8: Train ----\n",
        "rf_model.fit(X_train, y_train)\n",
        "print(\"Random Forest pipeline trained (StandardScaler + OneHotEncoder -> RandomForestClassifier).\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ---- C9: Evaluate ----\n",
        "y_pred = rf_model.predict(X_test)\n",
        "y_proba = rf_model.predict_proba(X_test)[:, 1]\n",
        "\n",
        "acc = accuracy_score(y_test, y_pred)\n",
        "auc = roc_auc_score(y_test, y_proba)\n",
        "\n",
        "# Bootstrap 95% confidence interval for accuracy using scipy.stats.bootstrap\n",
        "correct = (y_pred == y_test.values).astype(float)\n",
        "boot_res = stats.bootstrap((correct,), np.mean, confidence_level=0.95,\n",
        "                            n_resamples=2000, random_state=RANDOM_STATE, method=\"basic\")\n",
        "ci_low, ci_high = boot_res.confidence_interval\n",
        "\n",
        "print(f\"Accuracy         : {acc:.3f}\")\n",
        "print(f\"ROC-AUC          : {auc:.3f}\")\n",
        "print(f\"Accuracy 95% CI  : [{ci_low:.3f}, {ci_high:.3f}]  (scipy.stats bootstrap, 2000 resamples)\")\n",
        "print(\"\\nClassification report:\")\n",
        "print(classification_report(y_test, y_pred, target_names=[\"Stayed on transit\", \"Switched to private vehicle\"]))"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ---- C10: Confusion matrix plot ----\n",
        "cm = confusion_matrix(y_test, y_pred)\n",
        "fig, ax = plt.subplots(figsize=(5.2, 4.6))\n",
        "im = ax.imshow(cm, cmap=\"viridis\")\n",
        "labels = [\"Stayed on\\ntransit\", \"Switched to\\nprivate vehicle\"]\n",
        "ax.set_xticks([0, 1]); ax.set_xticklabels(labels)\n",
        "ax.set_yticks([0, 1]); ax.set_yticklabels(labels)\n",
        "for i in range(2):\n",
        "    for j in range(2):\n",
        "        ax.text(j, i, f\"{cm[i, j]:,}\", ha=\"center\", va=\"center\",\n",
        "                color=\"white\" if cm[i, j] < cm.max()*0.6 else \"black\",\n",
        "                fontsize=14, fontweight=\"bold\")\n",
        "ax.set_title(\"Confusion Matrix \\u2014 Random Forest (test set)\", fontsize=13)\n",
        "ax.set_xlabel(\"Predicted\"); ax.set_ylabel(\"Actual\")\n",
        "fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)\n",
        "plt.tight_layout()\n",
        "plt.savefig(f\"{ASSETS}/fig_confusion_matrix.png\", dpi=115, bbox_inches=\"tight\")\n",
        "plt.show()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ---- C11: Feature importance plot ----\n",
        "ohe = rf_model.named_steps[\"preprocessor\"].named_transformers_[\"cat\"].named_steps[\"onehot\"]\n",
        "cat_names = list(ohe.get_feature_names_out(CATEGORICAL_FEATURES))\n",
        "all_feature_names = NUMERIC_FEATURES + cat_names\n",
        "importances = rf_model.named_steps[\"classifier\"].feature_importances_\n",
        "imp_series = pd.Series(importances, index=all_feature_names).sort_values(ascending=False)\n",
        "top_imp = imp_series.head(15)[::-1]\n",
        "\n",
        "fig, ax = plt.subplots(figsize=(8, 6.5))\n",
        "bars = ax.barh(top_imp.index, top_imp.values, color=ACCENT, edgecolor=\"white\", linewidth=0.4)\n",
        "ax.set_title(\"Top 15 Feature Importances \\u2014 Random Forest\", fontsize=13)\n",
        "ax.set_xlabel(\"Relative importance\")\n",
        "for b, v in zip(bars, top_imp.values):\n",
        "    ax.text(v + top_imp.values.max()*0.01, b.get_y() + b.get_height()/2, f\"{v:.3f}\",\n",
        "            va=\"center\", fontsize=9)\n",
        "plt.tight_layout()\n",
        "plt.savefig(f\"{ASSETS}/fig_feature_importance.png\", dpi=115, bbox_inches=\"tight\")\n",
        "plt.show()\n",
        "print(\"Top 5 drivers of a commuter switching to a private vehicle:\")\n",
        "print(imp_series.head(5))"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ---- C12: Node-level risk aggregation (all cities) ----\n",
        "X_full_proc = df[FEATURES].copy()\n",
        "df[\"predicted_switch_risk\"] = rf_model.predict_proba(X_full_proc)[:, 1]\n",
        "\n",
        "node_summary = (\n",
        "    df.groupby([\"transit_node_id\", \"city\", \"node_type\", \"node_latitude\", \"node_longitude\"])\n",
        "    .agg(\n",
        "        trips=(\"record_id\", \"count\"),\n",
        "        predicted_risk=(\"predicted_switch_risk\", \"mean\"),\n",
        "        actual_switch_rate=(\"switched_to_private_vehicle\", \"mean\"),\n",
        "        avg_congestion=(\"congestion_index_node\", \"mean\"),\n",
        "        avg_crowding=(\"crowding_index\", \"mean\"),\n",
        "        avg_wait_min=(\"avg_wait_time_min\", \"mean\"),\n",
        "        avg_alt_mode_availability=(\"alt_mode_availability_score\", \"mean\"),\n",
        "        avg_safety_score=(\"safety_perception_score\", \"mean\"),\n",
        "        avg_infra_score=(\"last_mile_infra_score\", \"mean\"),\n",
        "    )\n",
        "    .reset_index()\n",
        "    .sort_values(\"predicted_risk\", ascending=False)\n",
        ")\n",
        "print(f\"Aggregated {len(node_summary)} transit nodes.\")\n",
        "print(\"\\nTop 10 highest-risk nodes nationally:\")\n",
        "print(node_summary[[\"transit_node_id\", \"city\", \"node_type\", \"trips\", \"predicted_risk\"]].head(10).to_string(index=False))"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ---- C13: Top 15 highest-risk nodes chart (Pune highlighted) ----\n",
        "top15 = node_summary.head(15).iloc[::-1]\n",
        "colors = [ACCENT_2 if c == \"Pune\" else ACCENT_3 for c in top15[\"city\"]]\n",
        "fig, ax = plt.subplots(figsize=(8.5, 7))\n",
        "bars = ax.barh(top15[\"transit_node_id\"] + \"  (\" + top15[\"city\"] + \")\", top15[\"predicted_risk\"]*100,\n",
        "                color=colors, edgecolor=\"white\", linewidth=0.4)\n",
        "ax.set_xlabel(\"Predicted probability of switching to private vehicle (%)\")\n",
        "ax.set_title(\"Top 15 Highest-Congestion / Highest-Defection Nodes\\n(coral = Pune)\", fontsize=13)\n",
        "for b, v in zip(bars, top15[\"predicted_risk\"]*100):\n",
        "    ax.text(v + 0.5, b.get_y() + b.get_height()/2, f\"{v:.1f}%\", va=\"center\", fontsize=9)\n",
        "plt.tight_layout()\n",
        "plt.savefig(f\"{ASSETS}/fig_top15_nodes.png\", dpi=115, bbox_inches=\"tight\")\n",
        "plt.show()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ---- C14: Pune-focused ranking ----\n",
        "pune_nodes = node_summary[node_summary.city == \"Pune\"].sort_values(\"predicted_risk\", ascending=False).reset_index(drop=True)\n",
        "pune_nodes.insert(0, \"pune_rank\", np.arange(1, len(pune_nodes) + 1))\n",
        "print(f\"Pune has {len(pune_nodes)} transit nodes in the dataset.\")\n",
        "print(\"\\nAll Pune nodes ranked by predicted last-mile defection risk:\")\n",
        "print(pune_nodes[[\"pune_rank\", \"transit_node_id\", \"node_type\", \"trips\", \"predicted_risk\",\n",
        "                   \"avg_wait_min\", \"avg_alt_mode_availability\"]].round(3).to_string(index=False))"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ---- C15: Pune geo risk map (matplotlib scatter as base for a live map) ----\n",
        "fig, ax = plt.subplots(figsize=(7.5, 7))\n",
        "sizes = 60 + (pune_nodes[\"trips\"] / pune_nodes[\"trips\"].max()) * 260\n",
        "sc = ax.scatter(\n",
        "    pune_nodes[\"node_longitude\"], pune_nodes[\"node_latitude\"],\n",
        "    s=sizes, c=pune_nodes[\"predicted_risk\"]*100, cmap=\"plasma\",\n",
        "    edgecolor=\"white\", linewidth=0.8, alpha=0.92, zorder=3,\n",
        ")\n",
        "for _, r in pune_nodes.head(5).iterrows():\n",
        "    ax.annotate(r[\"transit_node_id\"], (r[\"node_longitude\"], r[\"node_latitude\"]),\n",
        "                textcoords=\"offset points\", xytext=(6, 6), fontsize=8, color=\"white\", fontweight=\"bold\")\n",
        "ax.set_facecolor(\"#141821\")\n",
        "ax.set_title(\"Pune \\u2014 Last-Mile Defection Risk by Transit Node\\n(bubble size = trip volume, colour = risk)\", fontsize=12.5)\n",
        "ax.set_xlabel(\"Longitude\"); ax.set_ylabel(\"Latitude\")\n",
        "cbar = fig.colorbar(sc, ax=ax, fraction=0.046, pad=0.04)\n",
        "cbar.set_label(\"Predicted switch risk (%)\")\n",
        "plt.tight_layout()\n",
        "plt.savefig(f\"{ASSETS}/fig_pune_map.png\", dpi=115, bbox_inches=\"tight\")\n",
        "plt.show()\n",
        "print(\"Note: this scatter plot uses raw node coordinates as a stand-in for a live map.\")\n",
        "print(\"In the Lovable web app, plot these same lat/lon + risk values on an actual satellite/\")\n",
        "print(\"street basemap (e.g. Mapbox GL, Google Maps JS API) for an interactive version.\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ---- C16: Rule-based recommendation engine ----\n",
        "def recommend_interventions(node_row):\n",
        "    \"\"\"Given a row of node_summary, return a ranked list of concrete,\n",
        "    human-readable interventions targeting the specific weak points\n",
        "    of that node (not a generic checklist).\"\"\"\n",
        "    recs = []\n",
        "    if node_row[\"avg_alt_mode_availability\"] < 4.5:\n",
        "        recs.append(\"Increase supply of shared autos / e-rickshaws or add a feeder-bus route\")\n",
        "    if node_row[\"avg_wait_min\"] > 14:\n",
        "        recs.append(\"Reduce feeder-bus/auto headway, especially during peak hours\")\n",
        "    if node_row[\"avg_crowding\"] > 0.55:\n",
        "        recs.append(\"Deploy additional-capacity buses to relieve platform/stand crowding\")\n",
        "    if node_row[\"avg_safety_score\"] < 5.5:\n",
        "        recs.append(\"Improve lighting, signage and visible safety presence around the node\")\n",
        "    if node_row[\"avg_infra_score\"] < 0.45:\n",
        "        recs.append(\"Upgrade footpaths, covered walkways and last-mile pedestrian infrastructure\")\n",
        "    if not recs:\n",
        "        recs.append(\"Monitor \\u2014 node is currently within acceptable service parameters\")\n",
        "    return recs\n",
        "\n",
        "pune_nodes[\"recommendations\"] = pune_nodes.apply(recommend_interventions, axis=1)\n",
        "print(\"Sample recommendations for the 5 highest-risk Pune nodes:\\n\")\n",
        "for _, r in pune_nodes.head(5).iterrows():\n",
        "    print(f\"{r['transit_node_id']}  ({r['node_type']})  \\u2014 risk {r['predicted_risk']*100:.1f}%\")\n",
        "    for rec in r[\"recommendations\"]:\n",
        "        print(f\"   \\u2022 {rec}\")\n",
        "    print()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ---- C17: Demonstration \\u2014 single commuter prediction function ----\n",
        "def predict_switch_risk(commuter_input: dict) -> dict:\n",
        "    \"\"\"Takes a single commuter/trip description (dict) and returns the\n",
        "    model's predicted probability of switching to a private vehicle,\n",
        "    plus the relevant node-level recommendations if a known node is given.\"\"\"\n",
        "    row = {f: commuter_input.get(f, np.nan) for f in FEATURES}\n",
        "    row_df = pd.DataFrame([row])\n",
        "    risk = float(rf_model.predict_proba(row_df)[:, 1][0])\n",
        "    result = {\"predicted_switch_probability\": round(risk, 3),\n",
        "              \"risk_label\": \"High\" if risk > 0.6 else \"Moderate\" if risk > 0.35 else \"Low\"}\n",
        "    return result\n",
        "\n",
        "demo_input = {\n",
        "    \"city\": \"Pune\", \"node_type\": \"Metro Station\", \"time_of_day\": \"Evening Peak (17-20)\",\n",
        "    \"day_type\": \"Weekday\", \"weather_condition\": \"Heavy Rain\",\n",
        "    \"distance_to_final_destination_km\": 3.2, \"avg_wait_time_min\": 18.0,\n",
        "    \"transit_headway_min\": 9.0, \"crowding_index\": 0.72, \"congestion_index_node\": 0.68,\n",
        "    \"last_mile_fare_inr\": 45.0, \"walk_time_min\": 22.0, \"alt_mode_availability_score\": 3.1,\n",
        "    \"app_cab_wait_time_min\": 11.0, \"safety_perception_score\": 4.8, \"last_mile_infra_score\": 0.35,\n",
        "    \"previous_negative_experience\": 1, \"trip_satisfaction_score\": 4.0,\n",
        "    \"node_latitude\": 18.55, \"node_longitude\": 73.86,\n",
        "    \"commuter_age_group\": \"25-34\", \"commuter_gender\": \"Female\",\n",
        "    \"commuter_income_bracket\": \"Middle\", \"trip_purpose\": \"Work Commute\",\n",
        "}\n",
        "print(\"Demo commuter (Pune, evening peak, heavy rain, poor last-mile options):\")\n",
        "print(json.dumps(predict_switch_risk(demo_input), indent=2))"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ---- C18: Save model + export artifacts for the Lovable frontend ----\n",
        "model_path = os.path.join(OUT, \"transit_switch_rf_model.joblib\")\n",
        "joblib.dump(rf_model, model_path)\n",
        "\n",
        "node_summary_path = os.path.join(OUT, \"node_level_summary.csv\")\n",
        "node_summary.to_csv(node_summary_path, index=False)\n",
        "\n",
        "pune_export = pune_nodes[[\n",
        "    \"transit_node_id\", \"node_type\", \"node_latitude\", \"node_longitude\", \"trips\",\n",
        "    \"predicted_risk\", \"actual_switch_rate\", \"avg_congestion\", \"avg_crowding\",\n",
        "    \"avg_wait_min\", \"avg_alt_mode_availability\", \"recommendations\"\n",
        "]].rename(columns={\n",
        "    \"transit_node_id\": \"id\", \"node_latitude\": \"lat\", \"node_longitude\": \"lng\",\n",
        "    \"predicted_risk\": \"risk_score\",\n",
        "})\n",
        "pune_export[\"risk_score\"] = (pune_export[\"risk_score\"] * 100).round(1)\n",
        "pune_export[\"actual_switch_rate\"] = (pune_export[\"actual_switch_rate\"] * 100).round(1)\n",
        "pune_json_path = os.path.join(OUT, \"pune_high_risk_nodes.json\")\n",
        "pune_export.to_json(pune_json_path, orient=\"records\", indent=2)\n",
        "\n",
        "print(\"Saved artifacts for downstream use:\")\n",
        "print(f\"  - Trained model      : {model_path}\")\n",
        "print(f\"  - Full node summary  : {node_summary_path}\")\n",
        "print(f\"  - Pune frontend feed : {pune_json_path}\")\n",
        "print(f\"\\nPreview of {os.path.basename(pune_json_path)}:\")\n",
        "print(json.dumps(json.loads(pune_export.head(2).to_json(orient=\"records\")), indent=2))"
      ]
    }
  ]
}

with open("model_notebook.ipynb", "w") as f:
    json.dump(notebook, f, indent=2)

print("Saved model_notebook.ipynb successfully!")
